[package]
name = "bldc-driver-rp2350"
version = "0.1.0"
edition = "2024"

[dependencies]

panic-probe = { workspace = true }
embassy-usb-logger = { workspace = true }
embassy-usb = { workspace = true }
log = { workspace = true }

embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-io = { workspace = true }
embedded-io-async = { workspace = true }
embedded-storage = { workspace = true }

embassy-executor = { workspace = true }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }

cortex-m-rt = "0.7.3"
cortex-m = { version = "0.7.6" }
embassy-rp = { version = "0.10.0", features = [
  "unstable-pac",
  "time-driver",
  "critical-section-impl",
  "rp235xa",
] }

fixed = { version = "1.31.0" }

bldc-driver-hal = { path = "../bldc-driver-hal" }

[profile.release]
debug = 2
lto = true
opt-level = 'z'

[profile.dev]
debug = 2
lto = true
opt-level = "z"
