[package]
name = "bldc-driver-hal"
version = "0.1.0"
edition = "2024"

[dependencies]

panic-probe = { workspace = true }
embassy-usb-logger = { workspace = true }
embassy-usb = { workspace = true }
log = { workspace = true }

embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-io = { workspace = true }
embedded-io-async = { workspace = true }
embedded-storage = { workspace = true }

embassy-executor = { workspace = true }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }
